### ISSUE TITLE
Morning peer-to-peer review 10March,22

### ISSUE THREAD

**Issue by cynthiainga** [Nemwel-Boniface/openSourceLibrary#32]
Hi @Nemwel-Boniface and @zmekonnen251 
Your project looks good so far :+1:  but there is something you can improve.

- Your styling is good but if you make more styling to your home page your project will look better
- Please make sure that your README.md file has a proper documentation

By the way you did a great job :clap:  :clap:

**Comment by zmekonnen251** [comment]
Thank you @cynthiainga and @iLynette for your constructive feedback :+1: :100:  . we accepted all of the required changes.
